# Generated by Django 5.0.1 on 2024-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_kyc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='./static/assests/images/profile.jpeg', upload_to='kyc'),
        ),
    ]
