# Generated by Django 5.0.1 on 2024-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('master', 'master'), ('visa', 'visa')], default='master', max_length=20),
        ),
    ]
